name: XRNX Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Zip repository
        run: zip -r org.lackluster.Paketti_V3.54.xrnx .

      - name: Upload XRNX as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: packaged-xrnx
          path: org.lackluster.Paketti_V3.54.xrnx
